#!/usr/bin/env python3
"""Generate embedded land spans from Natural Earth v5.1.2 ne_110m_land.geojson.
Usage: python3 scripts/generate_setup_world_map.py /path/to/ne_110m_land.geojson
"""
import json, math, sys
from pathlib import Path
j=json.loads(Path(sys.argv[1]).read_text())
rings=[]
for f in j['features']:
 g=f['geometry']; polygons=[g['coordinates']] if g['type']=='Polygon' else g['coordinates']
 for polygon in polygons: rings.append(polygon)
spans=[]
for row in range(180):
 lat=89.5-row
 for polygon in rings:
  hits=[]
  for ring in polygon:
   for (x1,y1),(x2,y2) in zip(ring,ring[1:]):
    if (y1>lat)!=(y2>lat): hits.append(x1+(lat-y1)*(x2-x1)/(y2-y1))
  hits.sort()
  for left,right in zip(hits[::2],hits[1::2]):
   a=max(0,math.ceil(left+179.5)); b=min(359,math.floor(right+179.5))
   if b>=a: spans.append((row,a,b))
p=Path('src/ui/setup_world_map_data.h')
p.write_text('/* Natural Earth v5.1.2, public domain, ne_110m_land.geojson.\n * https://github.com/nvkelso/natural-earth-vector/blob/v5.1.2/geojson/ne_110m_land.geojson\n * Equirectangular land spans sampled at one degree; each row is north to south.\n * Generated by scripts/generate_setup_world_map.py. */\nstatic const uint16_t setup_land_spans[][3] = {\n'+''.join('    { %d, %d, %d },\n'%s for s in spans)+'};\n')
print(len(spans))
