#ifndef REMOTE_CONTROL_WEBAPP_H
#define REMOTE_CONTROL_WEBAPP_H

/* Remote-control web application HTML/CSS/JS. Persistent playback panel
 * polling /api/status, and bottom-nav tabs for Library, Queue, and Playlists. */
static const char * const REMOTE_CONTROL_APP_HTML =
    "<!DOCTYPE html><html><head><meta charset=\"utf-8\">"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
    "<title>Compás Remote Control</title><style>"
    "*{box-sizing:border-box}"
    ":root{color-scheme:dark;--bg:#0d0e13;--panel:#171820;--line:#30313b;--muted:#a3a1a8;--accent:#9acb46;--accent-strong:#789b39;--accent-soft:#26351a;--maxw:1500px}"
    "body{background:radial-gradient(ellipse at 18% 0%,#182231 0,transparent 42%),var(--bg);color:#f4f6fa;"
    "font-family:system-ui,-apple-system,Segoe UI,sans-serif;text-align:left;margin:0;padding:28px 24px 104px}"
    "button,input{font:inherit}button{color:inherit}button:focus-visible,input:focus-visible,#bar:focus-visible,[tabindex]:focus-visible{"
    "outline:3px solid var(--accent);outline-offset:3px}"
    "#brandbar{max-width:var(--maxw);margin:0 auto 18px;display:flex;align-items:center;gap:12px;height:58px;border-bottom:1px solid var(--line)}"
    ".brandmark{width:34px;height:34px;border:1px solid #46572e;border-radius:9px;display:flex;align-items:end;justify-content:center;gap:3px;padding:7px;background:#151a13}"
    ".brandmark i{width:3px;border-radius:2px 2px 0 0;background:var(--accent);box-shadow:0 0 8px #9acb4655}.brandmark i:nth-child(1){height:8px}.brandmark i:nth-child(2){height:15px}.brandmark i:nth-child(3){height:10px}.brandmark i:nth-child(4){height:17px}.brandmark i:nth-child(5){height:7px}"
    ".brandname{font-weight:750;letter-spacing:.02em}.brandname small{display:block;font-size:.62rem;letter-spacing:.18em;text-transform:uppercase;color:var(--muted)}"
    "#themeToggle{margin-left:auto;min-height:40px;padding:8px 12px;border:1px solid var(--line);border-radius:999px;background:var(--panel);cursor:pointer;color:inherit}"
    "#app{max-width:var(--maxw);margin:0 auto;display:grid;grid-template-columns:205px minmax(400px,1fr) 330px;grid-template-areas:'browse player upcoming';gap:26px;align-items:stretch}"
    ".panel{background:linear-gradient(145deg,#191f29,#11151c);border:1px solid var(--line);border-radius:20px;padding:24px;min-width:0;box-shadow:0 18px 50px #0003}"
    ".eyebrow{font-size:.73rem;letter-spacing:.14em;text-transform:uppercase;color:var(--accent);font-weight:700;margin:0 0 18px}"
    "#player{text-align:center;position:relative;isolation:isolate;overflow:hidden;grid-area:player;padding:24px 34px;background:linear-gradient(145deg,#25291e,#11140f)}"
    "#art{display:block;position:absolute;z-index:-2;inset:0;width:100%;height:100%;object-fit:cover;border-radius:inherit;margin:0;"
    "background:radial-gradient(circle at 68% 28%,#b98b4d 0 8%,transparent 8.5%),radial-gradient(ellipse at 70% 94%,#435232 0 34%,transparent 35%),linear-gradient(135deg,#39392b,#171a15);box-shadow:none}"
    "#player:before{content:'';position:absolute;z-index:-1;inset:0;background:linear-gradient(90deg,rgba(10,11,10,.96) 0%,rgba(12,13,11,.83) 48%,rgba(12,13,11,.3) 100%),linear-gradient(0deg,rgba(8,9,8,.88),transparent 68%);pointer-events:none}"
    "#player>*:not(#art){position:relative;z-index:1}"
    "#title{font-size:clamp(1.35rem,2.3vw,2rem);line-height:1.2;margin:0 0 8px;overflow-wrap:anywhere}"
    "#artist,#album{color:var(--muted);margin:3px 0;font-size:.95rem}#album{font-size:.85rem}"
    "#bar{background:#303744;border-radius:8px;height:8px;margin:26px 0 9px;overflow:hidden;cursor:pointer;touch-action:manipulation}"
    "#fill{background:linear-gradient(90deg,var(--accent-strong),var(--accent));height:100%;width:0%;border-radius:inherit}"
    "#time{color:var(--muted);font-size:.8rem;display:flex;justify-content:space-between;margin:0}"
    "#controls{margin:26px 0 20px;display:flex;justify-content:center;align-items:center;gap:12px}"
    "#controls button{background:#242820;border:1px solid #4a5140;color:#f0f2e9;border-radius:50%;width:52px;height:52px;"
    "display:flex;align-items:center;justify-content:center;padding:0;cursor:pointer;transition:background .15s,transform .15s}"
    "#controls button:hover{background:#333a2b}#controls button:active{transform:scale(.96)}"
    "#controls #playbtn{width:66px;height:66px;background:var(--accent);color:#17200f;border:0}#controls #playbtn:hover{background:#b2d66b}"
    "#controls svg{width:42%;height:42%;fill:currentColor}#modebtn svg{width:48%;height:48%}"
    "#modeLabel{color:var(--muted);font-size:.8rem;margin:0 0 20px}"
    "#volumeRow{display:flex;align-items:center;gap:12px;max-width:380px;margin:0 auto;color:var(--muted);font-size:.85em}"
    "#volumeRow input{flex:1;accent-color:var(--accent);min-width:0}"
    "#browse{grid-area:browse;min-height:0;scroll-margin-top:12px;padding:20px 16px;transition:opacity .2s ease,transform .2s ease}#browse .eyebrow{margin-bottom:8px}"
    "#search{display:block;width:100%;margin:18px 0 8px;padding:13px 15px;border-radius:10px;"
    "border:1px solid #394353;background:#0e1218;color:#f4f6fa;font-size:1em}#search::placeholder{color:#818c9c}"
    "#libHeader{margin:14px 0 0;display:flex;justify-content:space-between;align-items:center;padding:8px 0;color:var(--accent)}"
    "#libBack{padding:8px 10px;margin-left:-10px;border-radius:8px;background:none;border:0;color:var(--accent);font:inherit;cursor:pointer;min-height:44px}#libBack:hover{background:#ffffff0c}"
    "#libHeader #libTitle{color:#c1cad7;font-size:.9em;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-left:12px}"
    "#content{margin:10px 0 0}#content.view-enter{animation:contentEnter .2s ease both}@keyframes contentEnter{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}#content.menu{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:18px}"
    "#content:not(.menu){text-align:left;max-height:min(62vh,620px);overflow-y:auto;overscroll-behavior:contain;padding-right:3px}"
    ".tile{background:#1b222d;border:1px solid #303a48;border-radius:14px;min-height:112px;padding:18px 10px;display:flex;"
    "flex-direction:column;align-items:center;justify-content:center;gap:11px;cursor:pointer;color:#eee}"
    ".tile:hover{background:#242d39}.tile img{width:34px;height:34px}.tile span{font-size:.92em;font-weight:600}.empty{color:var(--muted);padding:18px 4px;text-align:center}"
    ".row{min-height:62px;padding:9px 8px;border-bottom:1px solid #252b34;display:flex;align-items:center;gap:8px}"
    ".row:hover{background:#ffffff08}.row .name{flex:1;color:#eee;cursor:pointer;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:10px 4px;background:none;border:0;text-align:left;font:inherit}"
    ".row .count{color:var(--muted);font-size:.8em;padding-left:8px}.row .thumb{width:44px;height:44px;border-radius:7px;object-fit:cover;margin-right:3px;"
    "background:#222936;flex-shrink:0}.row .info{flex:1;min-width:0;cursor:pointer;padding:5px 0;background:none;border:0;text-align:left;font:inherit}"
    ".row .t{color:#f1f4f9;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row .a{color:var(--muted);font-size:.82em;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;margin-top:3px}"
    ".row .action{background:transparent;border:1px solid transparent;color:var(--accent);font-size:.78em;font-weight:600;min-width:48px;min-height:44px;"
    "padding:8px 7px;cursor:pointer;flex-shrink:0;border-radius:9px}.row .action:hover{background:#293446;border-color:#3b4b64}"
    "#more{display:block;width:100%;color:var(--accent);font-size:.88em;text-align:center;padding:16px;cursor:pointer;border-radius:8px;background:transparent;border:0;font:inherit}#more:hover{background:#ffffff08}"
    ".queuePager{display:flex;justify-content:space-between;gap:10px;padding:10px 2px}.queuePager button{min-height:42px;padding:8px 13px;border-radius:9px;border:1px solid var(--line);background:var(--panel);color:var(--accent);cursor:pointer}"
    "#playlistPicker{display:none;position:fixed;inset:0;background:#000b;align-items:center;justify-content:center;z-index:5;padding:18px}"
    "#playlistPicker .box{background:#191f29;border:1px solid #3a4351;border-radius:16px;padding:22px;width:min(100%,400px);box-shadow:0 20px 60px #0009}"
    "#playlistPicker select{width:100%;padding:12px;background:#0f1319;color:#eee;border:1px solid #424b58;border-radius:8px;margin:14px 0}"
    "#playlistPicker .buttons{display:flex;justify-content:flex-end;gap:10px}"
    "#playlistPicker button{padding:10px 16px;background:#252e3b;color:#eee;border:1px solid #454f5d;border-radius:8px;min-height:44px;cursor:pointer}"
    "#toast{position:fixed;left:50%;bottom:82px;transform:translateX(-50%);background:#303b4b;color:#fff;"
    "padding:12px 18px;border-radius:12px;display:none;z-index:9;max-width:90vw;box-shadow:0 8px 30px #0008}"
    "#bottomNav{position:fixed;bottom:0;left:0;right:0;min-height:66px;background:#11151c;border-top:1px solid #303744;"
    "display:flex;z-index:4;padding:6px 12px calc(6px + env(safe-area-inset-bottom));backdrop-filter:blur(16px)}"
    "#bottomNav button{flex:1;background:none;border:0;border-radius:10px;color:#a5afbd;font-size:.72em;font-weight:600;padding:5px 3px;min-height:52px;cursor:pointer;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px}#bottomNav img{width:19px;height:19px;object-fit:contain}"
    "#bottomNav button.active{color:#dceaff;background:#263448}"
    "#upcoming{grid-area:upcoming;min-width:0;padding:20px 16px}#upcomingHead{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:12px}#upcomingHead h2{font-size:1rem;margin:0}#upcomingHead button{color:var(--accent);background:none;border:0;cursor:pointer;min-height:44px}#queuePreview{max-height:calc(100vh - 240px);overflow:auto}#queuePreview .row{min-height:56px}#queuePreview .row .action{display:none}"
    "#quickNav{display:none;grid-area:quicknav}#quickNav button{display:flex;align-items:center;gap:10px;width:100%;min-height:52px;padding:9px 10px;border:1px solid #303a48;border-radius:12px;background:#1b222d;color:inherit;text-align:left;font:inherit;font-size:.86rem;cursor:pointer}#quickNav button:hover{background:#242d39}#quickNav img{width:24px;height:24px;object-fit:contain}"
    "@media(min-width:761px){body{padding:0 30px 30px}#app{min-height:calc(100vh - 145px);grid-template-rows:minmax(590px,1fr)}#player,#upcoming,#browse{height:100%}#player{padding:28px 38px;text-align:left;display:flex;flex-direction:column;justify-content:center;align-items:flex-start}#player .eyebrow{letter-spacing:.18em;margin-bottom:18px}#title{font:500 clamp(2rem,3vw,3.1rem)/1.02 Georgia,serif;letter-spacing:-.03em;max-width:75%;text-shadow:0 2px 18px #000b}#artist,#album{text-shadow:0 1px 12px #000}#bar{width:100%;margin:25px 0 9px;background:#ffffff50}#time{width:100%;color:#e2e2d9}#controls{width:100%;justify-content:flex-start;gap:17px;margin:15px 0 8px}#controls button{width:50px;height:50px;background:#151911aa;border-color:#ffffff45}#controls #playbtn{width:60px;height:60px;background:var(--accent);color:#17200f;border:0}#modeLabel{margin:0 0 12px}#volumeRow{width:100%;max-width:none;justify-content:flex-start;color:#ebece5}#volumeRow input{max-width:220px}#bottomNav{display:none}#browse .eyebrow{font-size:.68rem}#content.menu{grid-template-columns:1fr;gap:6px}.tile{min-height:48px;flex-direction:row;justify-content:flex-start;padding:10px 12px}.tile img{width:22px;height:22px}}"
    "@media(max-width:760px){body{padding:0 14px calc(88px + env(safe-area-inset-bottom))}#brandbar{height:52px;margin-bottom:12px}#app{display:grid;grid-template-columns:minmax(0,1fr);grid-template-areas:'player' 'upcoming' 'browse';gap:14px}#browse{display:none}body.browsing #browse{display:block}"
    ".panel{width:100%;border-radius:16px;padding:16px}#player{position:static}#player .eyebrow{margin-bottom:8px}"
    "#art{width:min(52vw,190px);margin-bottom:12px}#title{font-size:1.35rem;margin-bottom:5px}#artist,#album{margin:2px 0}"
    "#bar{margin:14px 0 6px}#controls{gap:10px;margin:12px 0 10px}#controls button{width:48px;height:48px}#controls #playbtn{width:58px;height:58px}"
    "#modeLabel{margin-bottom:10px}#player{padding:16px}#player:before{display:none}#art{position:relative;z-index:auto;inset:auto;height:auto;width:min(32vw,120px);float:left;margin:0 14px 10px 0;border-radius:10px}#player:after{content:'';display:block;clear:both}#player .eyebrow{text-align:left}#title,#artist,#album{text-align:left}#bar{clear:both}#upcoming{order:0}#queuePreview{max-height:none}"
    "#browse{min-height:360px}#content:not(.menu){max-height:none;overflow:visible}.row{min-height:64px}}"
    "@media(max-width:380px){body{padding-left:10px;padding-right:10px}.panel{padding:15px}#controls{gap:7px}#controls button{width:46px;height:46px}"
    "#controls #playbtn{width:58px;height:58px}.row .action{min-width:42px;font-size:.72em;padding:6px 4px}}"
    "body[data-theme='light']{color:#252920;background:radial-gradient(ellipse at 18% 0%,#f0f1e9 0,transparent 42%),#f6f7f1;--accent:#718a4e;--accent-strong:#536b38;--accent-soft:#eaf0e1}"
    "body[data-theme='light'] .panel{background:#fff;border-color:#e4e6dc;box-shadow:0 12px 32px #36402d12}body[data-theme='light'] #player{background:linear-gradient(145deg,#25291e,#11140f)}"
    "body[data-theme='light'] #brandbar{border-color:#e1e4d9}body[data-theme='light'] .brandmark{background:#f1f4e9;border-color:#dce5c9}body[data-theme='light'] #themeToggle{background:#fff;border-color:#dfe3d7}"
    "body[data-theme='light'] #player{background:#dfe4d5}body[data-theme='light'] #player:before{background:linear-gradient(90deg,rgba(22,26,18,.89) 0%,rgba(27,31,23,.72) 48%,rgba(27,31,23,.22) 100%),linear-gradient(0deg,rgba(18,21,16,.75),transparent 68%)}body[data-theme='light'] #player #title,body[data-theme='light'] #player #artist,body[data-theme='light'] #player #album,body[data-theme='light'] #player #modeLabel{color:#fff}"
    "body[data-theme='light'] #controls button{background:#20251aaa;border-color:#ffffff66;color:#fff}body[data-theme='light'] #controls #playbtn{background:var(--accent);color:#fff}"
    "body[data-theme='light'] #bar{background:#ffffff70}body[data-theme='light'] #fill{background:linear-gradient(90deg,var(--accent-strong),#aac97e)}"
    "body[data-theme='light'] #search{background:#fafbf7;color:#252920;border-color:#dfe3d8}body[data-theme='light'] .tile{background:#fafbf7;border-color:#e3e6dc;color:#30352c}"
    "body[data-theme='light'] .row{border-color:#eceee7}body[data-theme='light'] .row .name,body[data-theme='light'] .row .info,body[data-theme='light'] .row .t{color:#252920}body[data-theme='light'] .row:hover{background:#f5f6f0}"
    "body[data-theme='light'] #libHeader #libTitle{color:#555b50}body[data-theme='light'] #playlistPicker .box{background:#fff;border-color:#dfe3d8;color:#252920}body[data-theme='light'] #playlistPicker select{background:#fafbf7;color:#252920;border-color:#dfe3d8}body[data-theme='light'] #playlistPicker button{background:#f1f3ec;color:#252920;border-color:#d9ded1}"
    "body[data-theme='light'] #bottomNav{background:#fff;border-color:#e1e4d9}body[data-theme='light'] #bottomNav button{color:#646a5f}body[data-theme='light'] #bottomNav button.active{color:#405b2c;background:#edf2e5}body[data-theme='light'] .row .thumb{background:#eceee7}"
    "body[data-theme='light'] #quickNav{background:linear-gradient(145deg,#fff,#f6f7f1);border-color:#e4e6dc}body[data-theme='light'] #quickNav button{background:#fafbf7;color:#30352c;border-color:#e3e6dc}body[data-theme='light'] #quickNav button:hover{background:#f2f4eb}body[data-theme='light'] .queuePager button{background:#fff}"
    "@media(min-width:1121px){body.browsing #app{grid-template-columns:205px minmax(400px,1fr) 330px;grid-template-rows:minmax(590px,1fr) auto;grid-template-areas:'quicknav player upcoming' 'browse browse browse'}body.browsing #quickNav{display:flex;flex-direction:column;gap:9px;padding:15px 12px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,#191f29,#11151c);box-shadow:0 18px 50px #0003;height:100%}body.browsing #browse{grid-area:browse;height:auto;min-height:260px;animation:browseEnter .22s ease both}body.browsing #content.menu{grid-template-columns:repeat(4,minmax(0,1fr))}@keyframes browseEnter{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}}"
    "@media(min-width:761px) and (max-width:1120px){#app{grid-template-columns:minmax(0,1fr) minmax(250px,31%);grid-template-areas:'player upcoming' 'browse browse';gap:18px;min-height:0;grid-template-rows:minmax(420px,auto) auto}#player,#upcoming,#browse{height:auto}#quickNav{display:none}body.browsing #app{grid-template-columns:minmax(0,1fr) minmax(250px,31%);grid-template-rows:minmax(420px,auto) auto;grid-template-areas:'player upcoming' 'browse browse'}body.browsing #browse{height:auto;min-height:260px}}"
    "@media(max-width:760px){body[data-theme='light'] #player{background:#fff;color:#252920}body[data-theme='light'] #player #title{color:#252920}body[data-theme='light'] #player #artist,body[data-theme='light'] #player #album,body[data-theme='light'] #player #modeLabel,body[data-theme='light'] #player #time,body[data-theme='light'] #player #volumeRow{color:#626b5d}body[data-theme='light'] #controls button{background:#f2f3ed;border-color:#dfe2d8;color:#384031}body[data-theme='light'] #controls #playbtn{background:var(--accent);color:#fff}}"
    "</style></head><body><header id=\"brandbar\"><span class=\"brandmark\" aria-hidden=\"true\"><i></i><i></i><i></i><i></i><i></i></span><span class=\"brandname\">Compás<small>Remote Control</small></span><button id=\"themeToggle\" type=\"button\" aria-label=\"Switch color theme\">Light mode</button></header><main id=\"app\"><section id=\"player\" class=\"panel\" aria-label=\"Now playing\">"
    "<p class=\"eyebrow\">Now playing</p><img id=\"art\" alt=\"Album artwork\">"
    "<h1 id=\"title\">Connecting to player…</h1><p id=\"artist\"></p><p id=\"album\"></p>"
    "<div id=\"bar\" role=\"slider\" tabindex=\"0\" aria-label=\"Seek playback position\" aria-valuemin=\"0\" aria-valuemax=\"100\" aria-valuenow=\"0\"><div id=\"fill\"></div></div><p id=\"time\"><span>0:00</span><span>0:00</span></p>"
    "<div id=\"controls\">"
    "<button aria-label=\"Previous track\" title=\"Previous track\" onclick=\"post('/api/playback/prev')\">"
    "<svg viewBox=\"0 0 24 24\"><path d=\"M6 6h2v12H6zm3.5 6 8.5 6V6z\"/></svg></button>"
    "<button id=\"playbtn\" aria-label=\"Play or pause\" title=\"Play or pause\" onclick=\"post('/api/playback/toggle')\">"
    "<svg viewBox=\"0 0 24 24\"><path d=\"M8 5v14l11-7z\"/></svg></button>"
    "<button aria-label=\"Next track\" title=\"Next track\" onclick=\"post('/api/playback/next')\">"
    "<svg viewBox=\"0 0 24 24\"><path d=\"M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z\"/></svg></button>"
    "<button id=\"modebtn\" aria-label=\"Playback mode\" title=\"Playback mode\" onclick=\"post('/api/playback/mode')\">"
    "<svg viewBox=\"0 0 24 24\"><rect x=\"4\" y=\"6\" width=\"16\" height=\"2.4\" rx=\"1.2\"/>"
    "<rect x=\"4\" y=\"11\" width=\"16\" height=\"2.4\" rx=\"1.2\"/>"
    "<rect x=\"4\" y=\"16\" width=\"10\" height=\"2.4\" rx=\"1.2\"/></svg></button>"
    "</div><p id=\"modeLabel\">Mode: <span id=\"modeText\">Sequential</span></p>"
    "<div id=\"volumeRow\"><label for=\"volume\">Volume</label><input type=\"range\" id=\"volume\" min=\"0\" max=\"100\" value=\"0\" aria-label=\"Volume\">"
    "</div>"
    "</section><section id=\"upcoming\" class=\"panel\" aria-label=\"Upcoming queue\"><div id=\"upcomingHead\"><h2>Up next</h2><button type=\"button\" onclick=\"navTo(showQueue)\">View queue →</button></div><div id=\"queuePreview\" aria-live=\"polite\"><p class=\"empty\">Loading queue…</p></div></section><nav id=\"quickNav\" aria-label=\"Library shortcuts\"><button type=\"button\" onclick=\"showAllSongs()\"><img data-rc-image=\"/assets/icon?name=all\" alt=\"\"><span>All Songs</span></button><button type=\"button\" onclick=\"showArtists()\"><img data-rc-image=\"/assets/icon?name=artist\" alt=\"\"><span>Artists</span></button><button type=\"button\" onclick=\"showAlbumArtists()\"><img data-rc-image=\"/assets/icon?name=album_artist\" alt=\"\"><span>Album Artists</span></button><button type=\"button\" onclick=\"showPlaylists()\"><img data-rc-image=\"/assets/icon?name=genre\" alt=\"\"><span>Playlists</span></button></nav><section id=\"browse\" class=\"panel\" aria-label=\"Browse music\"><p class=\"eyebrow\">Your music</p>"
    "<div id=\"libHeader\" style=\"display:none\">"
    "<button type=\"button\" id=\"libBack\">&larr; Back</button><span id=\"libTitle\"></span></div>"
    "<input type=\"search\" id=\"search\" aria-label=\"Search songs\" placeholder=\"Search your library\" style=\"display:none\">"
    "<div id=\"content\" aria-live=\"polite\"></div></section></main>"
    "<div id=\"playlistPicker\"><div class=\"box\"><div>Add to playlist</div>"
    "<select id=\"playlistSelect\"></select><div class=\"buttons\">"
    "<button onclick=\"closePlaylistPicker()\">Cancel</button>"
    "<button onclick=\"saveToSelectedPlaylist()\">Add</button></div></div></div>"
    "<div id=\"toast\" role=\"status\" aria-live=\"polite\"></div>"
    "<nav id=\"bottomNav\" aria-label=\"Main navigation\">"
    "<button id=\"navLibrary\" aria-label=\"All songs\" onclick=\"navTo(showAllSongs)\"><img data-rc-image=\"/assets/icon?name=all\" alt=\"\"><span>All Songs</span></button>"
    "<button id=\"navArtists\" aria-label=\"Artists\" onclick=\"navTo(showArtists)\"><img data-rc-image=\"/assets/icon?name=artist\" alt=\"\"><span>Artists</span></button>"
    "<button id=\"navAlbumArtists\" aria-label=\"Album artists\" onclick=\"navTo(showAlbumArtists)\"><img data-rc-image=\"/assets/icon?name=album_artist\" alt=\"\"><span>Album Artists</span></button>"
    "<button id=\"navPlaylists\" aria-label=\"Playlists\" onclick=\"navTo(showPlaylists)\"><img data-rc-image=\"/assets/icon?name=genre\" alt=\"\"><span>Playlists</span></button></nav>"
    "<script>"
    /* One fetch wrapper keeps browser requests on the same PIN contract as the Android client. */
    "var rcNativeFetch=window.fetch.bind(window),rcPinKey='compas-remote-pin',rcPinPrompt=null,rcPinPromptUntil=0;"
    "function rcAskPin(){if(rcPinPrompt)return rcPinPrompt;if(Date.now()<rcPinPromptUntil)return Promise.resolve(null);rcPinPrompt=new Promise(function(resolve){"
    "var value=window.prompt('Enter the PIN shown on your player under Wireless > Remote Control');"
    "resolve(value&&/^\\d{4,12}$/.test(value)?value:null);});setTimeout(function(){rcPinPrompt=null;rcPinPromptUntil=Date.now()+30000;},4000);return rcPinPrompt;}"
    "window.fetch=function(input,init){var url=typeof input==='string'?input:input.url;"
    "if(url==='/'||url.indexOf('/api/v1/capabilities')===0)return rcNativeFetch(input,init);"
    "var options=Object.assign({},init||{}),headers=new Headers(options.headers||{}),pin=localStorage.getItem(rcPinKey);"
    "if(pin)headers.set('X-Compas-PIN',pin);options.headers=headers;"
    "return rcNativeFetch(input,options).then(function(response){if(response.status!==401)return response;"
    "return rcAskPin().then(function(entered){if(!entered)return response;localStorage.setItem(rcPinKey,entered);"
    "var retryHeaders=new Headers(options.headers||{});retryHeaders.set('X-Compas-PIN',entered);"
    "return rcNativeFetch(input,Object.assign({},options,{headers:retryHeaders})).then(function(retry){"
    "if(retry.status===401)localStorage.removeItem(rcPinKey);return retry;});});});};"
    "function rcSetImage(img,url){window.fetch(url).then(function(r){if(!r.ok)throw Error();return r.blob();})"
    ".then(function(blob){var objectUrl=URL.createObjectURL(blob);img.addEventListener('load',function(){URL.revokeObjectURL(objectUrl);},{once:true});"
    "img.addEventListener('error',function(){URL.revokeObjectURL(objectUrl);},{once:true});img.src=objectUrl;})"
    ".catch(function(){img.style.visibility='hidden';});}"
    "document.querySelectorAll('img[data-rc-image]').forEach(function(img){rcSetImage(img,img.getAttribute('data-rc-image'));});"
    "var themeKey='compas-remote-theme';function setTheme(t){document.body.setAttribute('data-theme',t);document.documentElement.style.colorScheme=t;var b=document.getElementById('themeToggle');b.textContent=t==='dark'?'Light mode':'Dark mode';b.setAttribute('aria-label','Switch to '+(t==='dark'?'light':'dark')+' color mode');}"
    "var savedTheme=localStorage.getItem(themeKey),initialTheme=savedTheme||(window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');setTheme(initialTheme);"
    "document.getElementById('themeToggle').onclick=function(){var next=document.body.getAttribute('data-theme')==='dark'?'light':'dark';localStorage.setItem(themeKey,next);setTheme(next);};"
    "var view='menu',artistKind=null,artistName=null,libOffset=0,libQuery='',playContext='',queueOffset=0,queueRevision=0;var QUEUE_PAGE_SIZE=25;"
    "function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML;}"
    "function toast(msg){var t=document.getElementById('toast');t.textContent=msg;t.style.display='block';"
    "clearTimeout(t._timer);t._timer=setTimeout(function(){t.style.display='none';},1800);}"
    "function post(path,okmsg){return fetch(path,{method:'POST'}).then(function(r){if(!r.ok){if(r.status===409&&path.indexOf('/api/queue/')===0){toast('Queue changed; refreshed.');setTimeout(function(){showQueue(queueOffset);refreshQueuePreview();},250);return false;}throw Error();}"
    "if(okmsg)toast(okmsg);if(path.indexOf('/api/queue/')===0||path.indexOf('/api/playback/queue')===0)setTimeout(refreshQueuePreview,250);return true;}).catch(function(){toast('Device request failed');return false;});}"
    "function activeNav(id){['navLibrary','navArtists','navAlbumArtists','navPlaylists'].forEach(function(n){"
    "var b=document.getElementById(n),active=n===id;b.classList.toggle('active',active);"
    "if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}"
    "function navTo(fn){fn();}"
    "var pendingPlaylistIndex=-1;"
    "function addToPlaylist(index){pendingPlaylistIndex=index;"
    "fetch('/api/playlists').then(r=>r.json()).then(function(d){"
    "var s=document.getElementById('playlistSelect');s.innerHTML='';"
    "d.playlists.filter(function(p){return p.writable!==false;}).forEach(function(p){var n=p.name.replace(/\\.m3u8?$/i,'');"
    "var o=document.createElement('option');o.value=n;o.textContent=n;s.appendChild(o);});"
    "var o=document.createElement('option');o.value='__new__';o.textContent='Create new playlist...';s.appendChild(o);"
    "document.getElementById('playlistPicker').style.display='flex';}).catch(()=>{});}"
    "function closePlaylistPicker(){document.getElementById('playlistPicker').style.display='none';pendingPlaylistIndex=-1;}"
    "function saveToSelectedPlaylist(){var s=document.getElementById('playlistSelect'),name=s.value;"
    "var creating=name==='__new__';if(creating){name=prompt('New playlist name:');if(!name)return;}"
    "var index=pendingPlaylistIndex,url=(creating?'/api/playlists':'/api/playlists/add')+'?name='+encodeURIComponent(name)+'&index='+index;"
    "fetch(url,{method:'POST'}).then(function(r){return r.text().then(function(t){"
    "if(!r.ok)toast('Failed: '+t);else{closePlaylistPicker();toast(creating?'Playlist created':'Added to playlist');}});"
    "}).catch(function(){toast('Device request failed');});}"
    "function setHeader(visible,title){"
    "document.body.classList.toggle('browsing',visible);"
    "document.getElementById('libHeader').style.display=visible?'flex':'none';"
    "document.getElementById('libTitle').textContent=title||'';"
    "document.getElementById('search').style.display='none';var content=document.getElementById('content');content.classList.remove('view-enter');void content.offsetWidth;content.classList.add('view-enter');"
    "setTimeout(function(){content.classList.remove('view-enter');},260);if(visible)requestAnimationFrame(function(){document.getElementById('browse').scrollIntoView({behavior:'smooth',block:'start'});});}"
    "function renderRows(items,renderFn){"
    "var el=document.getElementById('content');el.className='';void el.offsetWidth;el.className='view-enter';el.innerHTML='';"
    "items.forEach(function(item){el.appendChild(renderFn(item));});}"
    "function refreshQueuePage(offset){setTimeout(function(){showQueue(offset);refreshQueuePreview();},250);}"
    "function refreshQueuePreview(){var el=document.getElementById('queuePreview');fetch('/api/queue?offset=0&limit=12').then(r=>r.json()).then(function(d){el.innerHTML='';"
    "if(!d.songs.length){el.innerHTML='<p class=\"empty\">Queue is empty.</p>';return;}"
    "d.songs.slice(0,12).forEach(function(s,i){var row=document.createElement('div');row.className='row';var n=document.createElement('span');n.className='count';n.textContent=(i+1)+'.';"
    "var thumb=document.createElement('img');thumb.className='thumb';thumb.alt='';thumb.loading='lazy';rcSetImage(thumb,'/api/art?index='+s.index);thumb.onerror=function(){thumb.style.visibility='hidden';};"
    "var info=document.createElement('div');info.className='info';var t=document.createElement('div');t.className='t';t.textContent=s.title||'Unknown track';var a=document.createElement('div');a.className='a';a.textContent=s.artist||'';info.appendChild(t);info.appendChild(a);row.appendChild(n);row.appendChild(thumb);row.appendChild(info);el.appendChild(row);});"
    "if(d.total>12){var more=document.createElement('p');more.className='empty';more.textContent=(d.total-12)+' more tracks';el.appendChild(more);}}).catch(function(){el.innerHTML='<p class=\"empty\">Queue unavailable.</p>';});}"
    "function nameRow(name,count,onClick,thumbIndex){"
    "var row=document.createElement('div');row.className='row';"
    "if(thumbIndex!==undefined){"
    "var thumb=document.createElement('img');thumb.className='thumb';thumb.loading='lazy';thumb.alt='';"
    "thumb.onerror=function(){thumb.style.visibility='hidden';};"
    "rcSetImage(thumb,'/api/art?index='+thumbIndex);"
    "row.appendChild(thumb);}"
    "var nm=document.createElement('button');nm.type='button';nm.className='name';nm.textContent=name;"
    "row.appendChild(nm);"
    "if(count!==undefined){var c=document.createElement('div');c.className='count';c.textContent=count;"
    "row.appendChild(c);}"
    "row.onclick=onClick;return row;}"
    "function songRow(s){"
    "var row=document.createElement('div');row.className='row';"
    "var thumb=document.createElement('img');thumb.className='thumb';thumb.loading='lazy';thumb.alt='';"
    "thumb.onerror=function(){thumb.style.visibility='hidden';};"
    "rcSetImage(thumb,'/api/art?index='+s.index);"
    "var info=document.createElement('button');info.type='button';info.className='info';info.setAttribute('aria-label','Play '+s.title+' by '+s.artist);"
    "info.innerHTML='<div class=\"t\">'+esc(s.title)+'</div><div class=\"a\">'+esc(s.artist)+'</div>';"
    "info.onclick=function(){post('/api/playback/play?index='+s.index+playContext);};"
    "var queue=document.createElement('button');queue.type='button';queue.className='action';queue.title='Add to queue';queue.setAttribute('aria-label','Add '+s.title+' to queue');queue.textContent='Queue';"
    "queue.onclick=function(e){e.stopPropagation();post('/api/playback/queue?index='+s.index,'Added to queue');};"
    "var add=document.createElement('button');add.type='button';add.className='action';add.title='Add to playlist';add.setAttribute('aria-label','Add '+s.title+' to playlist');add.textContent='Playlist';"
    "add.onclick=function(e){e.stopPropagation();addToPlaylist(s.index);};"
    "row.appendChild(thumb);row.appendChild(info);row.appendChild(queue);row.appendChild(add);return row;}"
    "var MENU_ITEMS=["
    "{icon:'all',label:'All Songs',onclick:function(){showAllSongs();}},"
    "{icon:'artist',label:'Artists',onclick:function(){showArtists();}},"
    "{icon:'album_artist',label:'Album Artists',onclick:function(){showAlbumArtists();}},"
    "{icon:'genre',label:'Playlists',onclick:function(){showPlaylists();}}];"
    "function showMenu(){"
    "view='menu';activeNav('');setHeader(false);"
    "var el=document.getElementById('content');el.className='menu';el.innerHTML='';"
    "MENU_ITEMS.forEach(function(m){"
    "var tile=document.createElement('button');tile.type='button';tile.className='tile';"
    "var img=document.createElement('img');rcSetImage(img,'/assets/icon?name='+m.icon);img.alt='';"
    "var label=document.createElement('span');label.textContent=m.label;"
    "tile.appendChild(img);tile.appendChild(label);tile.onclick=m.onclick;"
    "el.appendChild(tile);});}"
    "function showArtists(){"
    "view='artists';activeNav('navArtists');setHeader(true,'Artists');"
    "document.getElementById('content').innerHTML='<p class=\"empty\">Loading artists…</p>';"
    "fetch('/api/library/artists').then(r=>r.json()).then(function(d){"
    "renderRows(d.artists,function(a){return nameRow(a.name,a.count,function(){showArtistAlbums('artist',a.name);});"
    "});if(!d.artists.length)document.getElementById('content').innerHTML='<p class=\"empty\">No artists found.</p>';}).catch(function(){document.getElementById('content').innerHTML='<p class=\"empty\">Could not load artists.</p>';});}"
    "function showAlbumArtists(){"
    "view='album_artists';activeNav('navAlbumArtists');setHeader(true,'Album Artists');"
    "document.getElementById('content').innerHTML='<p class=\"empty\">Loading album artists…</p>';"
    "fetch('/api/library/album_artists').then(r=>r.json()).then(function(d){"
    "renderRows(d.artists,function(a){return nameRow(a.name,a.count,"
    "function(){showArtistAlbums('album_artist',a.name);});});if(!d.artists.length)document.getElementById('content').innerHTML='<p class=\"empty\">No album artists found.</p>';}).catch(function(){document.getElementById('content').innerHTML='<p class=\"empty\">Could not load album artists.</p>';});}"
    "function showPlaylists(){"
    "view='playlists';activeNav('navPlaylists');setHeader(true,'Playlists');"
    "document.getElementById('content').innerHTML='<p class=\"empty\">Loading playlists…</p>';"
    "fetch('/api/playlists').then(r=>r.json()).then(function(d){"
    "renderRows(d.playlists,function(p){var n=p.name.replace(/\\.m3u8?$/i,''),key=p.key||n;"
    "return nameRow(n,undefined,function(){showPlaylistSongs(key,n);});});if(!d.playlists.length)document.getElementById('content').innerHTML='<p class=\"empty\">No playlists yet.</p>';}).catch(function(){document.getElementById('content').innerHTML='<p class=\"empty\">Could not load playlists.</p>';});}"
    "function showArtistAlbums(kind,name){"
    "view='artist_albums';artistKind=kind;artistName=name;activeNav(kind==='artist'?'navArtists':'navAlbumArtists');setHeader(true,name);"
    "document.getElementById('content').innerHTML='<p class=\"empty\">Loading albums…</p>';"
    "var url='/api/library/albums?'+(kind==='artist'?'artist=':'album_artist=')+encodeURIComponent(name);"
    "fetch(url).then(r=>r.json()).then(function(d){"
    "renderRows(d.albums,function(a){return nameRow(a.name,a.count,function(){showAlbumSongs(a.name);},a.index);});"
    "if(!d.albums.length)document.getElementById('content').innerHTML='<p class=\"empty\">No albums found.</p>';"
    "}).catch(function(){document.getElementById('content').innerHTML='<p class=\"empty\">Could not load albums.</p>';});}"
    "function showAlbumSongs(album){"
    "view='album_songs';setHeader(true,album);"
    "document.getElementById('content').innerHTML='<p class=\"empty\">Loading songs…</p>';"
    "var kindParam=(artistKind==='artist'?'artist=':'album_artist=')+encodeURIComponent(artistName);"
    "playContext='&'+kindParam+'&album='+encodeURIComponent(album);"
    "var url='/api/library?limit=200&'+kindParam+'&album='+encodeURIComponent(album);"
    "fetch(url).then(r=>r.json()).then(function(d){renderRows(d.songs,songRow);if(!d.songs.length)document.getElementById('content').innerHTML='<p class=\"empty\">No songs in this album.</p>';}).catch(function(){document.getElementById('content').innerHTML='<p class=\"empty\">Could not load songs.</p>';});}"
    "function showPlaylistSongs(key,label){"
    "view='playlist_songs';setHeader(true,label||key);"
    "document.getElementById('content').innerHTML='<p class=\"empty\">Loading songs…</p>';"
    "playContext='&playlist='+encodeURIComponent(key);"
    "fetch('/api/playlists/songs?name='+encodeURIComponent(key)).then(r=>r.json()).then(function(d){"
    "renderRows(d.songs,songRow);if(!d.songs.length)document.getElementById('content').innerHTML='<p class=\"empty\">This playlist is empty.</p>';}).catch(function(){document.getElementById('content').innerHTML='<p class=\"empty\">Could not load playlist songs.</p>';});}"
    "function showAllSongs(){"
    "view='all_songs';setHeader(true,'All Songs');playContext='';"
    "var s=document.getElementById('search');s.style.display='block';s.value='';libQuery='';"
    "loadLibrary(true);}"
    "function showQueue(offset){view='queue';queueOffset=Math.max(0,offset||0);activeNav('');setHeader(true,'Queue');"
    "var el=document.getElementById('content');el.className='';void el.offsetWidth;el.className='view-enter';el.innerHTML='<p class=\"empty\">Loading queue…</p>';"
    "fetch('/api/queue?offset='+queueOffset+'&limit='+QUEUE_PAGE_SIZE).then(r=>r.json()).then(function(d){queueRevision=d.revision;el.innerHTML='';"
    "if(!d.songs.length){el.innerHTML='<p class=\"empty\">Queue is empty.</p>';return;}"
    "d.songs.forEach(function(s){var row=songRow(s);var actions=row.querySelectorAll('.action');"
    "actions.forEach(function(a){a.remove();});var del=document.createElement('button');del.type='button';del.className='action';del.setAttribute('aria-label','Remove '+s.title+' from queue');"
    "del.textContent='Remove';del.onclick=function(e){e.stopPropagation();post('/api/queue/remove?offset='+s.offset+'&revision='+queueRevision,'Removed from queue').then(function(ok){if(ok){var nextOffset=queueOffset;if(d.songs.length===1&&queueOffset>0)nextOffset=Math.max(0,queueOffset-QUEUE_PAGE_SIZE);refreshQueuePage(nextOffset);}});};"
    "row.appendChild(del);el.appendChild(row);});"
    "var summary=document.createElement('p');summary.className='empty';summary.textContent='Showing '+(queueOffset+1)+'–'+(queueOffset+d.songs.length)+' of '+d.total+' tracks';el.appendChild(summary);"
    "if(d.total>QUEUE_PAGE_SIZE){var pager=document.createElement('div');pager.className='queuePager';"
    "if(queueOffset>0){var prev=document.createElement('button');prev.type='button';prev.textContent='← Previous 25';prev.onclick=function(){showQueue(Math.max(0,queueOffset-QUEUE_PAGE_SIZE));};pager.appendChild(prev);}"
    "if(queueOffset+d.songs.length<d.total){var next=document.createElement('button');next.type='button';next.textContent='Next 25 →';next.onclick=function(){showQueue(queueOffset+QUEUE_PAGE_SIZE);};pager.appendChild(next);}el.appendChild(pager);}"
    "var clear=document.createElement('button');clear.type='button';clear.id='more';clear.textContent='Clear queue';"
    "clear.onclick=function(){post('/api/queue/clear?revision='+queueRevision,'Queue cleared').then(function(ok){if(ok){queueOffset=0;refreshQueuePage(0);}});};el.appendChild(clear);"
    "}).catch(function(){el.innerHTML='<p class=\"empty\">Could not load queue.</p>';"
    "var retry=document.createElement('button');retry.type='button';retry.id='more';retry.textContent='Retry';retry.onclick=function(){showQueue(queueOffset);};el.appendChild(retry);});}"
    "function loadLibrary(reset){"
    "if(reset){libOffset=0;var c=document.getElementById('content');c.className='view-enter';c.innerHTML='';}"
    "if(reset)document.getElementById('content').innerHTML='<p class=\"empty\">Loading songs…</p>';"
    "var url='/api/library?offset='+libOffset+'&limit=50&q='+encodeURIComponent(libQuery);"
    "fetch(url).then(r=>r.json()).then(d=>{"
    "var el=document.getElementById('content');"
    "var old=document.getElementById('more');if(old)old.remove();"
    "if(reset)el.innerHTML='';"
    "d.songs.forEach(function(s){el.appendChild(songRow(s));});"
    "if(reset&&!d.songs.length)el.innerHTML='<p class=\"empty\">No matching songs found.</p>';"
    "libOffset+=d.songs.length;"
    "if(libOffset<d.total){"
    "var more=document.createElement('button');more.type='button';more.id='more';more.textContent='Load more ('+(d.total-libOffset)+' more)';"
    "more.onclick=function(){loadLibrary(false);};el.appendChild(more);}"
    "}).catch(function(){document.getElementById('content').innerHTML='<p class=\"empty\">Could not load songs.</p>';});}"
    "document.getElementById('libBack').onclick=function(){"
    "if(view==='artist_albums'){if(artistKind==='artist')showArtists();else showAlbumArtists();}"
    "else if(view==='album_songs'){showArtistAlbums(artistKind,artistName);}"
    "else if(view==='playlist_songs'){showPlaylists();}"
    "else{showMenu();}};"
    "var searchTimer=null;"
    "document.getElementById('search').addEventListener('input',function(){"
    "libQuery=this.value;clearTimeout(searchTimer);searchTimer=setTimeout(function(){loadLibrary(true);},300);});"
    "showMenu();refreshQueuePreview();setInterval(refreshQueuePreview,15000);"
    "</script>"
    "<script>"
    "var dragging=false,lastArtKey='',hadStatus=false;"
    "var ICON_PLAY='<svg viewBox=\"0 0 24 24\"><path d=\"M8 5v14l11-7z\"/></svg>';"
    "var ICON_PAUSE='<svg viewBox=\"0 0 24 24\"><path d=\"M6 5h4v14H6zM14 5h4v14h-4z\"/></svg>';"
    /* Same one-button cycle as the player screen's own order_icon
     * (Sequential -> Repeat All -> Repeat One -> Shuffle), indexed by
     * play_mode_t's own int values -- see remote_control.h's own comment
     * on remote_control_notify_status()'s play_mode param. Repeat All/One
     * share a circle-with-gap-plus-arrowhead glyph (stroke-dasharray
     * leaves a small opening, the polygon caps it with an arrowhead);
     * Repeat One adds a "1". Shuffle is a plain crossing-lines glyph. */
    "var MODE_ICONS=["
    "'<svg viewBox=\"0 0 24 24\"><rect x=\"4\" y=\"6\" width=\"16\" height=\"2.4\" rx=\"1.2\"/>"
    "<rect x=\"4\" y=\"11\" width=\"16\" height=\"2.4\" rx=\"1.2\"/>"
    "<rect x=\"4\" y=\"16\" width=\"10\" height=\"2.4\" rx=\"1.2\"/></svg>',"
    "'<svg viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\" "
    "stroke-width=\"2\" stroke-dasharray=\"43 7\"/><polygon points=\"12,3 16,7 12,7\"/></svg>',"
    "'<svg viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\" "
    "stroke-width=\"2\" stroke-dasharray=\"43 7\"/><polygon points=\"12,3 16,7 12,7\"/>"
    "<text x=\"12\" y=\"16\" font-size=\"8\" text-anchor=\"middle\">1</text></svg>',"
    "'<svg viewBox=\"0 0 24 24\"><path d=\"M4 6l16 12M20 6 4 18\" stroke=\"currentColor\" "
    "stroke-width=\"2.2\" fill=\"none\" stroke-linecap=\"round\"/></svg>'];"
    "function fmt(s){s=Math.max(0,s|0);var m=(s/60)|0,r=s%60;return m+':'+(r<10?'0':'')+r;}"
    "function poll(){fetch('/api/status').then(function(r){if(r.status===401)throw Error('pin');if(!r.ok)throw Error('network');return r.json();}).then(d=>{"
    "hadStatus=true;"
    "document.getElementById('title').textContent=d.title||'(nothing playing)';"
    "document.getElementById('artist').textContent=d.artist||'';"
    "document.getElementById('album').textContent=d.album||'';"
    "window.lastDuration=d.duration_seconds;"
    "window.lastPosition=d.position_seconds;"
    "var pct=d.duration_seconds>0?(100*d.position_seconds/d.duration_seconds):0;"
    "document.getElementById('fill').style.width=pct+'%';"
    "document.getElementById('bar').setAttribute('aria-valuenow',Math.round(pct));"
    "var tm=document.getElementById('time');tm.children[0].textContent=fmt(d.position_seconds);tm.children[1].textContent=fmt(d.duration_seconds);"
    "var pb=document.getElementById('playbtn');pb.innerHTML=d.playing?ICON_PAUSE:ICON_PLAY;pb.setAttribute('aria-label',d.playing?'Pause playback':'Start playback');"
    "var mode=d.play_mode|0,modeNames=['Sequential','Repeat all','Repeat one','Shuffle'];"
    "document.getElementById('modebtn').innerHTML=MODE_ICONS[mode]||MODE_ICONS[0];"
    "document.getElementById('modebtn').setAttribute('aria-label','Playback mode: '+(modeNames[mode]||modeNames[0])+'; change mode');"
    "document.getElementById('modeText').textContent=modeNames[mode]||modeNames[0];"
    "if(!dragging)document.getElementById('volume').value=Math.round(d.volume*100);"
    "var artKey=(d.title||'')+'|'+(d.artist||'');"
    "if(artKey!==lastArtKey){lastArtKey=artKey;var art=document.getElementById('art');"
    "if(d.title){art.style.visibility='visible';art.onload=function(){art.style.visibility='visible';};"
    "art.onerror=function(){art.style.visibility='hidden';};"
    "rcSetImage(art,'/api/art?t='+Date.now());}else{art.style.visibility='hidden';art.removeAttribute('src');}}"
    "}).catch(function(e){if(e.message==='pin'){document.getElementById('title').textContent='PIN required';document.getElementById('artist').textContent='Enter the PIN shown on the player to connect.';return;}if(!hadStatus){document.getElementById('title').textContent='Player unavailable';document.getElementById('artist').textContent='Check the Wi-Fi connection and retry.';}});}"
    "document.getElementById('bar').addEventListener('click',function(e){"
    "var r=this.getBoundingClientRect();var frac=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));"
    "fetch('/api/playback/seek?seconds='+Math.round(frac*(window.lastDuration||0)),{method:'POST'});});"
    "document.getElementById('bar').addEventListener('keydown',function(e){if(e.key!=='ArrowLeft'&&e.key!=='ArrowRight')return;"
    "e.preventDefault();var step=Math.max(5,Math.round((window.lastDuration||0)/100));var pos=(window.lastPosition||0)+(e.key==='ArrowRight'?step:-step);"
    "fetch('/api/playback/seek?seconds='+Math.max(0,Math.min(window.lastDuration||0,pos)),{method:'POST'});});"
    "var vol=document.getElementById('volume');"
    "vol.addEventListener('input',function(){dragging=true;});"
    "vol.addEventListener('change',function(){dragging=false;post('/api/playback/volume?percent='+this.value);});"
    "poll();setInterval(poll,1000);"
    "</script></body></html>";

#endif /* REMOTE_CONTROL_WEBAPP_H */
