#ifndef REMOTE_CONTROL_WEBAPP_H
#define REMOTE_CONTROL_WEBAPP_H

/* Remote-control web application HTML/CSS/JS. Persistent playback header
 * polling /api/status, and bottom-nav tabs for Library, Queue, and Playlists. */
static const char * const REMOTE_CONTROL_APP_HTML =
    "<!DOCTYPE html><html><head><meta charset=\"utf-8\">"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
    "<title>Remote Control</title><style>"
    "*{box-sizing:border-box}"
    ":root{--maxw:480px}"
    "body{background:#111;color:#eee;font-family:sans-serif;text-align:center;"
    "padding:clamp(20px,6vw,40px) 16px 88px;margin:0}"
    "h1{font-size:1.4em;margin:0 0 4px}"
    "p{color:#aaa;margin:4px 0}"
    "#art{display:none;width:min(55vw,200px);height:min(55vw,200px);object-fit:cover;border-radius:12px;"
    "margin:0 auto 16px;background:#222}"
    "#bar{background:#333;border-radius:4px;height:6px;margin:24px auto;width:min(92vw,var(--maxw));"
    "overflow:hidden;cursor:pointer}"
    "#fill{background:#4da3ff;height:100%;width:0%}"
    "#time{color:#888;font-size:0.9em}"
    "#controls{margin:28px 0 16px;display:flex;justify-content:center;align-items:center;gap:clamp(12px,4vw,24px)}"
    "#controls button{background:#222;border:1px solid #444;color:#eee;border-radius:50%;"
    "width:clamp(48px,14vw,64px);height:clamp(48px,14vw,64px);display:flex;align-items:center;justify-content:center;"
    "padding:0;cursor:pointer}"
    "#controls button:active{background:#333}"
    "#controls svg{width:44%;height:44%;fill:currentColor}"
    "#volumeRow{display:flex;align-items:center;gap:10px;width:min(92vw,320px);margin:20px auto 0;"
    "color:#888;font-size:0.85em}"
    "#volumeRow input{flex:1}"
    "#search{display:block;width:min(92vw,var(--maxw));margin:24px auto 4px;padding:10px;border-radius:6px;"
    "border:1px solid #444;background:#1a1a1a;color:#eee;font-size:1em}"
    "#libHeader{width:min(92vw,var(--maxw));margin:16px auto 0;display:flex;justify-content:space-between;"
    "align-items:center;padding:8px 4px;color:#4da3ff;cursor:pointer}"
    "#libHeader #libTitle{color:#888;font-size:0.9em;overflow:hidden;text-overflow:ellipsis;"
    "white-space:nowrap;margin-left:12px}"
    "#content{width:min(92vw,var(--maxw));margin:8px auto 0}"
    "#content.menu{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:24px}"
    "#content:not(.menu){text-align:left;max-height:360px;overflow-y:auto}"
    ".tile{background:#1a1a1a;border:1px solid #333;border-radius:12px;padding:22px 8px;display:flex;"
    "flex-direction:column;align-items:center;gap:10px;cursor:pointer}"
    ".tile:active{background:#222}"
    ".tile img{width:40px;height:40px}"
    ".tile span{color:#eee;font-size:0.9em}"
    ".row{padding:10px 8px;border-bottom:1px solid #222;display:flex;align-items:center}"
    ".row:active{background:#222}"
    ".row .name{flex:1;color:#eee;cursor:pointer;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
    ".row .count{color:#888;font-size:0.85em;padding-left:8px}"
    ".row .thumb{width:40px;height:40px;border-radius:6px;object-fit:cover;margin-right:10px;"
    "background:#222;flex-shrink:0}"
    ".row .info{flex:1;min-width:0;cursor:pointer}"
    ".row .t{color:#eee;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
    ".row .a{color:#888;font-size:0.85em;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}"
    ".row .action{color:#4da3ff;font-size:1.1em;padding:8px;cursor:pointer;flex-shrink:0}"
    "#more{color:#888;font-size:0.85em;padding:10px;cursor:pointer}"
    "#playlistPicker{display:none;position:fixed;inset:0;background:#000b;align-items:center;justify-content:center;z-index:5}"
    "#playlistPicker .box{background:#1b1b1b;border:1px solid #444;border-radius:12px;padding:18px;width:min(88vw,360px)}"
    "#playlistPicker select{width:100%;padding:11px;background:#111;color:#eee;border:1px solid #444;border-radius:6px;margin:12px 0}"
    "#playlistPicker .buttons{display:flex;justify-content:flex-end;gap:10px}"
    "#playlistPicker button{padding:9px 14px;background:#222;color:#eee;border:1px solid #444;border-radius:6px}"
    "#toast{position:fixed;left:50%;bottom:76px;transform:translateX(-50%);background:#333;color:#fff;"
    "padding:10px 16px;border-radius:20px;display:none;z-index:9;max-width:90vw}"
    "#bottomNav{position:fixed;bottom:0;left:0;right:0;height:64px;background:#181818;border-top:1px solid #333;"
    "display:flex;z-index:4;padding-bottom:env(safe-area-inset-bottom)}"
    "#bottomNav button{flex:1;background:none;border:0;color:#999;font-size:.78em;padding:8px 2px}"
    "#bottomNav button.active{color:#4da3ff}"
    "</style></head><body>"
    "<img id=\"art\" alt=\"\">"
    "<h1 id=\"title\">--</h1><p id=\"artist\"></p><p id=\"album\"></p>"
    "<div id=\"bar\"><div id=\"fill\"></div></div><p id=\"time\"></p>"
    "<div id=\"controls\">"
    "<button onclick=\"post('/api/playback/prev')\">"
    "<svg viewBox=\"0 0 24 24\"><path d=\"M6 6h2v12H6zm3.5 6 8.5 6V6z\"/></svg></button>"
    "<button id=\"playbtn\" onclick=\"post('/api/playback/toggle')\">"
    "<svg viewBox=\"0 0 24 24\"><path d=\"M8 5v14l11-7z\"/></svg></button>"
    "<button onclick=\"post('/api/playback/next')\">"
    "<svg viewBox=\"0 0 24 24\"><path d=\"M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z\"/></svg></button>"
    "<button id=\"modebtn\" onclick=\"post('/api/playback/mode')\">"
    "<svg viewBox=\"0 0 24 24\"><rect x=\"4\" y=\"6\" width=\"16\" height=\"2.4\" rx=\"1.2\"/>"
    "<rect x=\"4\" y=\"11\" width=\"16\" height=\"2.4\" rx=\"1.2\"/>"
    "<rect x=\"4\" y=\"16\" width=\"10\" height=\"2.4\" rx=\"1.2\"/></svg></button>"
    "</div>"
    "<div id=\"volumeRow\"><span>Volume</span><input type=\"range\" id=\"volume\" min=\"0\" max=\"100\" value=\"0\">"
    "</div>"
    "<div id=\"libHeader\" style=\"display:none\">"
    "<span id=\"libBack\">&larr; Back</span><span id=\"libTitle\"></span></div>"
    "<input type=\"text\" id=\"search\" placeholder=\"Search library...\" style=\"display:none\">"
    "<div id=\"content\"></div>"
    "<div id=\"playlistPicker\"><div class=\"box\"><div>Add to playlist</div>"
    "<select id=\"playlistSelect\"></select><div class=\"buttons\">"
    "<button onclick=\"closePlaylistPicker()\">Cancel</button>"
    "<button onclick=\"saveToSelectedPlaylist()\">Add</button></div></div></div>"
    "<div id=\"toast\" role=\"status\" aria-live=\"polite\"></div>"
    "<nav id=\"bottomNav\" aria-label=\"Main navigation\">"
    "<button id=\"navLibrary\" onclick=\"showMenu()\">Library</button>"
    "<button id=\"navQueue\" onclick=\"showQueue()\">Queue</button>"
    "<button id=\"navPlaylists\" onclick=\"showPlaylists()\">Playlists</button></nav>"
    "<script>"
    "var view='menu',artistKind=null,artistName=null,libOffset=0,libQuery='',playContext='';"
    "function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML;}"
    "function toast(msg){var t=document.getElementById('toast');t.textContent=msg;t.style.display='block';"
    "clearTimeout(t._timer);t._timer=setTimeout(function(){t.style.display='none';},1800);}"
    "function post(path,okmsg){return fetch(path,{method:'POST'}).then(function(r){if(!r.ok)throw Error();"
    "if(okmsg)toast(okmsg);return r;}).catch(function(){toast('Device request failed');});}"
    "function activeNav(id){['navLibrary','navQueue','navPlaylists'].forEach(function(n){"
    "document.getElementById(n).classList.toggle('active',n===id);});}"
    "var pendingPlaylistIndex=-1;"
    "function addToPlaylist(index){pendingPlaylistIndex=index;"
    "fetch('/api/playlists').then(r=>r.json()).then(function(d){"
    "var s=document.getElementById('playlistSelect');s.innerHTML='';"
    "d.playlists.filter(function(p){return p.writable!==false;}).forEach(function(p){var n=p.name.replace(/\\.m3u8?$/i,'');"
    "var o=document.createElement('option');o.value=n;o.textContent=n;s.appendChild(o);});"
    "var o=document.createElement('option');o.value='__new__';o.textContent='Create new playlist...';s.appendChild(o);"
    "document.getElementById('playlistPicker').style.display='flex';}).catch(()=>{});}"
    "function closePlaylistPicker(){document.getElementById('playlistPicker').style.display='none';pendingPlaylistIndex=-1;}"
    "function saveToSelectedPlaylist(){var s=document.getElementById('playlistSelect'),name=s.value;"
    "var creating=name==='__new__';if(creating){name=prompt('New playlist name:');if(!name)return;}"
    "var index=pendingPlaylistIndex,url=(creating?'/api/playlists':'/api/playlists/add')+'?name='+encodeURIComponent(name)+'&index='+index;"
    "fetch(url,{method:'POST'}).then(function(r){return r.text().then(function(t){"
    "if(!r.ok)toast('Failed: '+t);else{closePlaylistPicker();toast(creating?'Playlist created':'Added to playlist');}});"
    "}).catch(function(){toast('Device request failed');});}"
    "function setHeader(visible,title){"
    "document.getElementById('libHeader').style.display=visible?'flex':'none';"
    "document.getElementById('libTitle').textContent=title||'';"
    "document.getElementById('search').style.display='none';}"
    "function renderRows(items,renderFn){"
    "var el=document.getElementById('content');el.className='';el.innerHTML='';"
    "items.forEach(function(item){el.appendChild(renderFn(item));});}"
    "function nameRow(name,count,onClick,thumbIndex){"
    "var row=document.createElement('div');row.className='row';"
    "if(thumbIndex!==undefined){"
    "var thumb=document.createElement('img');thumb.className='thumb';thumb.loading='lazy';thumb.alt='';"
    "thumb.onerror=function(){thumb.style.visibility='hidden';};"
    "thumb.src='/api/art?index='+thumbIndex;"
    "row.appendChild(thumb);}"
    "var nm=document.createElement('div');nm.className='name';nm.textContent=name;"
    "row.appendChild(nm);"
    "if(count!==undefined){var c=document.createElement('div');c.className='count';c.textContent=count;"
    "row.appendChild(c);}"
    "row.onclick=onClick;return row;}"
    "function songRow(s){"
    "var row=document.createElement('div');row.className='row';"
    "var thumb=document.createElement('img');thumb.className='thumb';thumb.loading='lazy';thumb.alt='';"
    "thumb.onerror=function(){thumb.style.visibility='hidden';};"
    "thumb.src='/api/art?index='+s.index;"
    "var info=document.createElement('div');info.className='info';"
    "info.innerHTML='<div class=\"t\">'+esc(s.title)+'</div><div class=\"a\">'+esc(s.artist)+'</div>';"
    "info.onclick=function(){post('/api/playback/play?index='+s.index+playContext);};"
    "var queue=document.createElement('div');queue.className='action';queue.title='Add to queue';queue.textContent='Q+';"
    "queue.onclick=function(e){e.stopPropagation();post('/api/playback/queue?index='+s.index,'Added to queue');};"
    "var add=document.createElement('div');add.className='action';add.title='Add to playlist';add.textContent='P+';"
    "add.onclick=function(e){e.stopPropagation();addToPlaylist(s.index);};"
    "row.appendChild(thumb);row.appendChild(info);row.appendChild(queue);row.appendChild(add);return row;}"
    "var MENU_ITEMS=["
    "{icon:'all',label:'All Songs',onclick:function(){showAllSongs();}},"
    "{icon:'artist',label:'Artists',onclick:function(){showArtists();}},"
    "{icon:'album_artist',label:'Album Artists',onclick:function(){showAlbumArtists();}},"
    "{icon:'genre',label:'Playlists',onclick:function(){showPlaylists();}}];"
    "function showMenu(){"
    "view='menu';activeNav('navLibrary');setHeader(false);"
    "var el=document.getElementById('content');el.className='menu';el.innerHTML='';"
    "MENU_ITEMS.forEach(function(m){"
    "var tile=document.createElement('div');tile.className='tile';"
    "var img=document.createElement('img');img.src='/assets/icon?name='+m.icon;img.alt='';"
    "var label=document.createElement('span');label.textContent=m.label;"
    "tile.appendChild(img);tile.appendChild(label);tile.onclick=m.onclick;"
    "el.appendChild(tile);});}"
    "function showArtists(){"
    "view='artists';setHeader(true,'Artists');"
    "fetch('/api/library/artists').then(r=>r.json()).then(function(d){"
    "renderRows(d.artists,function(a){return nameRow(a.name,a.count,function(){showArtistAlbums('artist',a.name);});"
    "});}).catch(()=>{});}"
    "function showAlbumArtists(){"
    "view='album_artists';setHeader(true,'Album Artists');"
    "fetch('/api/library/album_artists').then(r=>r.json()).then(function(d){"
    "renderRows(d.artists,function(a){return nameRow(a.name,a.count,"
    "function(){showArtistAlbums('album_artist',a.name);});});}).catch(()=>{});}"
    "function showPlaylists(){"
    "view='playlists';activeNav('navPlaylists');setHeader(true,'Playlists');"
    "fetch('/api/playlists').then(r=>r.json()).then(function(d){"
    "renderRows(d.playlists,function(p){var n=p.name.replace(/\\.m3u8?$/i,''),key=p.key||n;"
    "return nameRow(n,undefined,function(){showPlaylistSongs(key,n);});});}).catch(()=>{});}"
    "function showArtistAlbums(kind,name){"
    "view='artist_albums';artistKind=kind;artistName=name;setHeader(true,name);"
    "var url='/api/library/albums?'+(kind==='artist'?'artist=':'album_artist=')+encodeURIComponent(name);"
    "fetch(url).then(r=>r.json()).then(function(d){"
    "renderRows(d.albums,function(a){return nameRow(a.name,a.count,function(){showAlbumSongs(a.name);},a.index);});"
    "}).catch(()=>{});}"
    "function showAlbumSongs(album){"
    "view='album_songs';setHeader(true,album);"
    "var kindParam=(artistKind==='artist'?'artist=':'album_artist=')+encodeURIComponent(artistName);"
    "playContext='&'+kindParam+'&album='+encodeURIComponent(album);"
    "var url='/api/library?limit=200&'+kindParam+'&album='+encodeURIComponent(album);"
    "fetch(url).then(r=>r.json()).then(function(d){renderRows(d.songs,songRow);}).catch(()=>{});}"
    "function showPlaylistSongs(key,label){"
    "view='playlist_songs';setHeader(true,label||key);"
    "playContext='&playlist='+encodeURIComponent(key);"
    "fetch('/api/playlists/songs?name='+encodeURIComponent(key)).then(r=>r.json()).then(function(d){"
    "renderRows(d.songs,songRow);}).catch(()=>{});}"
    "function showAllSongs(){"
    "view='all_songs';setHeader(true,'All Songs');playContext='';"
    "var s=document.getElementById('search');s.style.display='block';s.value='';libQuery='';"
    "loadLibrary(true);}"
    "function showQueue(){view='queue';activeNav('navQueue');setHeader(false,'Queue');"
    "var el=document.getElementById('content');el.className='';el.innerHTML='<p>Loading queue...</p>';"
    "fetch('/api/queue').then(r=>r.json()).then(function(d){el.innerHTML='';"
    "if(!d.songs.length){el.innerHTML='<p>Queue is empty</p>';return;}"
    "d.songs.forEach(function(s){var row=songRow(s);var actions=row.querySelectorAll('.action');"
    "actions.forEach(function(a){a.remove();});var del=document.createElement('div');del.className='action';"
    "del.textContent='Remove';del.onclick=function(e){e.stopPropagation();post('/api/queue/remove?offset='+s.offset,'Removed from queue').then(showQueue);};"
    "row.appendChild(del);el.appendChild(row);});"
    "var clear=document.createElement('div');clear.id='more';clear.textContent='Clear queue';"
    "clear.onclick=function(){post('/api/queue/clear','Queue cleared').then(showQueue);};el.appendChild(clear);"
    "}).catch(function(){el.innerHTML='<p>Could not load queue. Tap to retry.</p>';el.onclick=showQueue;});}"
    "function loadLibrary(reset){"
    "if(reset){libOffset=0;var c=document.getElementById('content');c.className='';c.innerHTML='';}"
    "var url='/api/library?offset='+libOffset+'&limit=50&q='+encodeURIComponent(libQuery);"
    "fetch(url).then(r=>r.json()).then(d=>{"
    "var el=document.getElementById('content');"
    "var old=document.getElementById('more');if(old)old.remove();"
    "d.songs.forEach(function(s){el.appendChild(songRow(s));});"
    "libOffset+=d.songs.length;"
    "if(libOffset<d.total){"
    "var more=document.createElement('div');more.id='more';more.textContent='Load more ('+(d.total-libOffset)+' more)';"
    "more.onclick=function(){loadLibrary(false);};el.appendChild(more);}"
    "}).catch(()=>{});}"
    "document.getElementById('libBack').onclick=function(){"
    "if(view==='artist_albums'){if(artistKind==='artist')showArtists();else showAlbumArtists();}"
    "else if(view==='album_songs'){showArtistAlbums(artistKind,artistName);}"
    "else if(view==='playlist_songs'){showPlaylists();}"
    "else{showMenu();}};"
    "var searchTimer=null;"
    "document.getElementById('search').addEventListener('input',function(){"
    "libQuery=this.value;clearTimeout(searchTimer);searchTimer=setTimeout(function(){loadLibrary(true);},300);});"
    "showMenu();"
    "</script>"
    "<script>"
    "var dragging=false,lastArtKey='';"
    "var ICON_PLAY='<svg viewBox=\"0 0 24 24\"><path d=\"M8 5v14l11-7z\"/></svg>';"
    "var ICON_PAUSE='<svg viewBox=\"0 0 24 24\"><path d=\"M6 5h4v14H6zM14 5h4v14h-4z\"/></svg>';"
    /* Same one-button cycle as the player screen's own order_icon
     * (Sequential -> Repeat All -> Repeat One -> Shuffle), indexed by
     * play_mode_t's own int values -- see remote_control.h's own comment
     * on remote_control_notify_status()'s play_mode param. Repeat All/One
     * share a circle-with-gap-plus-arrowhead glyph (stroke-dasharray
     * leaves a small opening, the polygon caps it with an arrowhead);
     * Repeat One adds a "1". Shuffle is a plain crossing-lines glyph. */
    "var MODE_ICONS=["
    "'<svg viewBox=\"0 0 24 24\"><rect x=\"4\" y=\"6\" width=\"16\" height=\"2.4\" rx=\"1.2\"/>"
    "<rect x=\"4\" y=\"11\" width=\"16\" height=\"2.4\" rx=\"1.2\"/>"
    "<rect x=\"4\" y=\"16\" width=\"10\" height=\"2.4\" rx=\"1.2\"/></svg>',"
    "'<svg viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\" "
    "stroke-width=\"2\" stroke-dasharray=\"43 7\"/><polygon points=\"12,3 16,7 12,7\"/></svg>',"
    "'<svg viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"8\" fill=\"none\" stroke=\"currentColor\" "
    "stroke-width=\"2\" stroke-dasharray=\"43 7\"/><polygon points=\"12,3 16,7 12,7\"/>"
    "<text x=\"12\" y=\"16\" font-size=\"8\" text-anchor=\"middle\">1</text></svg>',"
    "'<svg viewBox=\"0 0 24 24\"><path d=\"M4 6l16 12M20 6 4 18\" stroke=\"currentColor\" "
    "stroke-width=\"2.2\" fill=\"none\" stroke-linecap=\"round\"/></svg>'];"
    "function fmt(s){s=Math.max(0,s|0);var m=(s/60)|0,r=s%60;return m+':'+(r<10?'0':'')+r;}"
    "function poll(){fetch('/api/status').then(r=>r.json()).then(d=>{"
    "document.getElementById('title').textContent=d.title||'(nothing playing)';"
    "document.getElementById('artist').textContent=d.artist||'';"
    "document.getElementById('album').textContent=d.album||'';"
    "window.lastDuration=d.duration_seconds;"
    "var pct=d.duration_seconds>0?(100*d.position_seconds/d.duration_seconds):0;"
    "document.getElementById('fill').style.width=pct+'%';"
    "document.getElementById('time').textContent=fmt(d.position_seconds)+' / '+fmt(d.duration_seconds);"
    "document.getElementById('playbtn').innerHTML=d.playing?ICON_PAUSE:ICON_PLAY;"
    "document.getElementById('modebtn').innerHTML=MODE_ICONS[d.play_mode]||MODE_ICONS[0];"
    "if(!dragging)document.getElementById('volume').value=Math.round(d.volume*100);"
    "var artKey=(d.title||'')+'|'+(d.artist||'');"
    "if(artKey!==lastArtKey){lastArtKey=artKey;var art=document.getElementById('art');"
    "if(d.title){art.onload=function(){art.style.display='block';};"
    "art.onerror=function(){art.style.display='none';};"
    "art.src='/api/art?t='+Date.now();}else{art.style.display='none';art.removeAttribute('src');}}"
    "}).catch(()=>{});}"
    "document.getElementById('bar').addEventListener('click',function(e){"
    "var r=this.getBoundingClientRect();var frac=(e.clientX-r.left)/r.width;"
    "fetch('/api/playback/seek?seconds='+Math.round(frac*(window.lastDuration||0)),{method:'POST'});});"
    "var vol=document.getElementById('volume');"
    "vol.addEventListener('input',function(){dragging=true;});"
    "vol.addEventListener('change',function(){dragging=false;post('/api/playback/volume?percent='+this.value);});"
    "poll();setInterval(poll,1000);"
    "</script></body></html>";

#endif /* REMOTE_CONTROL_WEBAPP_H */
